//! Каталог параметров llama-server.
//!
//! Содержит полный набор ключей из `llama-server --help` (см.
//! `docs/llama-server-help.md`). Используется страницей «Модели» как источник
//! метаданных для чипов, спин-боксов, дропдаунов и Info-Tooltip.
//!
//! Единственный источник правды: список `LLAMA_PARAMS`. Любой код UI и сериализации
//! должен искать параметр по `key` в этом списке.

#![allow(dead_code)]

// ─────────────────────────────────────────────────────────────────────────────
// Типы
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ParamCategory {
    Threads,
    Context,
    Attention,
    KvCache,
    Memory,
    Device,
    ModelLoading,
    Logging,
    Sampling,
    Server,
    ChatTemplate,
    Multimodal,
    Parallelism,
    Speculative,
    Tts,
    Other,
    Presets,
}

impl ParamCategory {
    pub const ALL: &'static [ParamCategory] = &[
        ParamCategory::Threads,
        ParamCategory::Context,
        ParamCategory::Attention,
        ParamCategory::KvCache,
        ParamCategory::Memory,
        ParamCategory::Device,
        ParamCategory::ModelLoading,
        ParamCategory::Logging,
        ParamCategory::Sampling,
        ParamCategory::Server,
        ParamCategory::ChatTemplate,
        ParamCategory::Multimodal,
        ParamCategory::Parallelism,
        ParamCategory::Speculative,
        ParamCategory::Tts,
        ParamCategory::Other,
        ParamCategory::Presets,
    ];

    pub fn label(self) -> &'static str {
        match self {
            ParamCategory::Threads => "Потоки и CPU",
            ParamCategory::Context => "Контекст",
            ParamCategory::Attention => "Attention / RoPE",
            ParamCategory::KvCache => "KV cache",
            ParamCategory::Memory => "Память и NUMA",
            ParamCategory::Device => "Устройства / GPU",
            ParamCategory::ModelLoading => "Загрузка модели",
            ParamCategory::Logging => "Логирование",
            ParamCategory::Sampling => "Sampling",
            ParamCategory::Server => "Сервер",
            ParamCategory::ChatTemplate => "Chat template",
            ParamCategory::Multimodal => "Multimodal",
            ParamCategory::Parallelism => "Параллелизм",
            ParamCategory::Speculative => "Speculative decoding",
            ParamCategory::Tts => "TTS / Voice",
            ParamCategory::Other => "Прочее",
            ParamCategory::Presets => "Готовые пресеты",
        }
    }
}

/// Тип контрола и вспомогательные метаданные для spin-box/toggle/dropdown.
#[derive(Clone, Copy, Debug)]
pub enum ParamKind {
    /// Целое число.
    Int { min: i64, max: i64, step: i64, default: i64 },
    /// Число с плавающей точкой.
    Float { min: f64, max: f64, step: f64, default: f64, decimals: u8 },
    /// Булевый флаг (on/off).
    Bool { default: bool },
    /// Текст (путь, имя, произвольная строка).
    Text { default: &'static str },
    /// Выбор из фиксированного набора.
    Enum {
        options: &'static [&'static str],
        default: &'static str,
    },
}

/// Описание одного параметра llama-server.
#[derive(Clone, Copy, Debug)]
pub struct LlamaParam {
    pub key: &'static str,
    pub cli: &'static str,
    pub aliases: &'static [&'static str],
    pub label: &'static str,
    pub description: &'static str,
    pub category: ParamCategory,
    pub kind: ParamKind,
    pub removable: bool,
    pub env: Option<&'static str>,
}

const fn int(min: i64, max: i64, step: i64, default: i64) -> ParamKind {
    ParamKind::Int { min, max, step, default }
}
const fn float(min: f64, max: f64, step: f64, decimals: u8, default: f64) -> ParamKind {
    ParamKind::Float { min, max, step, default, decimals }
}
const fn bool_k(default: bool) -> ParamKind {
    ParamKind::Bool { default }
}
const fn text_k(default: &'static str) -> ParamKind {
    ParamKind::Text { default }
}
const fn enum_k(options: &'static [&'static str], default: &'static str) -> ParamKind {
    ParamKind::Enum { options, default }
}

// Часто используемые константы
const CACHE_TYPES: &[&str] = &["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"];
const SPLIT_MODES: &[&str] = &["none", "layer", "row", "tensor"];
const ROPE_SCALING: &[&str] = &["none", "linear", "yarn"];
const POOLING_TYPES: &[&str] = &["none", "mean", "cls", "last", "rank"];
const NUMA_TYPES: &[&str] = &["distribute", "isolate", "numactl"];
const FLASH_ATTN: &[&str] = &["on", "off", "auto"];
const REASONING_FORMATS: &[&str] = &["auto", "none", "deepseek", "deepseek-legacy"];
const REASONING_MODES: &[&str] = &["on", "off", "auto"];
const LOG_COLORS: &[&str] = &["auto", "on", "off"];
const SPEC_TYPES: &[&str] = &[
    "none", "ngram-cache", "ngram-simple", "ngram-map-k", "ngram-map-k4v", "ngram-mod",
];
const CHAT_TEMPLATES: &[&str] = &[
    "bailing", "bailing-think", "bailing2", "chatglm3", "chatglm4", "chatml",
    "command-r", "deepseek", "deepseek-ocr", "deepseek2", "deepseek3", "exaone-moe",
    "exaone3", "exaone4", "falcon3", "gemma", "gigachat", "glmedge", "gpt-oss",
    "granite", "granite-4.0", "grok-2", "hunyuan-dense", "hunyuan-moe", "hunyuan-ocr",
    "kimi-k2", "llama2", "llama2-sys", "llama2-sys-bos", "llama2-sys-strip",
    "llama3", "llama4", "megrez", "minicpm", "mistral-v1", "mistral-v3",
    "mistral-v3-tekken", "mistral-v7", "mistral-v7-tekken", "monarch", "openchat",
    "orion", "pangu-embedded", "phi3", "phi4", "rwkv-world", "seed_oss", "smolvlm",
    "solar-open", "vicuna", "vicuna-orca", "yandex", "zephyr",
];

// ─────────────────────────────────────────────────────────────────────────────
// Полный список параметров
// ─────────────────────────────────────────────────────────────────────────────

/// Мелкий helper-макрос, чтобы писать записи компактно, без повтора полей по умолчанию.
macro_rules! lp {
    (
        key: $key:expr,
        cli: $cli:expr,
        $( aliases: $al:expr, )?
        label: $lbl:expr,
        description: $desc:expr,
        category: $cat:expr,
        kind: $kind:expr
        $(, env: $env:expr )?
        $(, removable: $rm:expr )?
        $(,)?
    ) => {
        LlamaParam {
            key: $key,
            cli: $cli,
            aliases: lp!(@aliases $( $al )? ),
            label: $lbl,
            description: $desc,
            category: $cat,
            kind: $kind,
            removable: lp!(@rm $( $rm )? ),
            env: lp!(@env $( $env )? ),
        }
    };
    (@aliases $al:expr) => { $al };
    (@aliases)          => { &[] };
    (@rm $rm:expr) => { $rm };
    (@rm)          => { true };
    (@env $env:expr) => { Some($env) };
    (@env)           => { None };
}

pub const LLAMA_PARAMS: &[LlamaParam] = &[
    // ─── Контекст (ctx_size — первый и неудаляемый, т.к. рендерится всегда) ───
    lp!(
        key: "ctx_size",
        cli: "--ctx-size",
        aliases: &["-c"],
        label: "Размер контекста",
        description: "Size of the prompt context (default: 0, 0 = loaded from model).\nОкно контекста в токенах. 0 — брать из модели.",
        category: ParamCategory::Context,
        kind: int(0, 1_000_000, 512, 4096),
        env: "LLAMA_ARG_CTX_SIZE",
        removable: false,
    ),
    lp!(
        key: "predict",
        cli: "--predict",
        aliases: &["-n", "--n-predict"],
        label: "Лимит токенов",
        description: "Number of tokens to predict (default: -1, -1 = infinity).",
        category: ParamCategory::Context,
        kind: int(-1, 1_000_000, 16, -1),
        env: "LLAMA_ARG_N_PREDICT",
    ),
    lp!(
        key: "batch_size",
        cli: "--batch-size",
        aliases: &["-b"],
        label: "Batch size",
        description: "Logical maximum batch size (default: 2048).",
        category: ParamCategory::Context,
        kind: int(1, 65536, 128, 2048),
        env: "LLAMA_ARG_BATCH",
    ),
    lp!(
        key: "ubatch_size",
        cli: "--ubatch-size",
        aliases: &["-ub"],
        label: "µBatch size",
        description: "Physical maximum batch size (default: 512).",
        category: ParamCategory::Context,
        kind: int(1, 65536, 64, 512),
        env: "LLAMA_ARG_UBATCH",
    ),
    lp!(
        key: "keep",
        cli: "--keep",
        label: "Keep токенов",
        description: "Number of tokens to keep from the initial prompt (default: 0, -1 = all).",
        category: ParamCategory::Context,
        kind: int(-1, 1_000_000, 16, 0),
    ),
    lp!(
        key: "swa_full",
        cli: "--swa-full",
        label: "SWA full",
        description: "Use full-size SWA cache (default: false).",
        category: ParamCategory::Context,
        kind: bool_k(false),
        env: "LLAMA_ARG_SWA_FULL",
    ),
    lp!(
        key: "escape",
        cli: "--escape",
        aliases: &["-e", "--no-escape"],
        label: "Process escapes",
        description: "Whether to process escapes sequences (\\n, \\r, \\t, \\\", \\\\). Default: true.",
        category: ParamCategory::Context,
        kind: bool_k(true),
    ),

    // ─── Потоки и CPU ────────────────────────────────────────────────────────
    lp!(
        key: "threads",
        cli: "--threads",
        aliases: &["-t"],
        label: "Потоки",
        description: "Number of CPU threads to use during generation (default: -1).",
        category: ParamCategory::Threads,
        kind: int(-1, 256, 1, -1),
        env: "LLAMA_ARG_THREADS",
    ),
    lp!(
        key: "threads_batch",
        cli: "--threads-batch",
        aliases: &["-tb"],
        label: "Потоки (batch)",
        description: "Number of threads to use during batch and prompt processing (default: same as --threads).",
        category: ParamCategory::Threads,
        kind: int(-1, 256, 1, -1),
    ),
    lp!(
        key: "cpu_mask",
        cli: "--cpu-mask",
        aliases: &["-C"],
        label: "CPU mask",
        description: "CPU affinity mask: arbitrarily long hex. Complements cpu-range.",
        category: ParamCategory::Threads,
        kind: text_k(""),
    ),
    lp!(
        key: "cpu_range",
        cli: "--cpu-range",
        aliases: &["-Cr"],
        label: "CPU range",
        description: "Range of CPUs for affinity, format lo-hi. Complements --cpu-mask.",
        category: ParamCategory::Threads,
        kind: text_k(""),
    ),
    lp!(
        key: "cpu_strict",
        cli: "--cpu-strict",
        label: "CPU strict",
        description: "Use strict CPU placement (default: 0).",
        category: ParamCategory::Threads,
        kind: int(0, 1, 1, 0),
    ),
    lp!(
        key: "prio",
        cli: "--prio",
        label: "Priority",
        description: "Process/thread priority: low(-1), normal(0), medium(1), high(2), realtime(3). Default 0.",
        category: ParamCategory::Threads,
        kind: int(-1, 3, 1, 0),
    ),
    lp!(
        key: "poll",
        cli: "--poll",
        label: "Poll level",
        description: "Polling level to wait for work (0 = no polling). Default 50.",
        category: ParamCategory::Threads,
        kind: int(0, 100, 5, 50),
    ),
    lp!(
        key: "cpu_mask_batch",
        cli: "--cpu-mask-batch",
        aliases: &["-Cb"],
        label: "CPU mask (batch)",
        description: "CPU affinity mask for batch phase. Defaults to --cpu-mask.",
        category: ParamCategory::Threads,
        kind: text_k(""),
    ),
    lp!(
        key: "cpu_range_batch",
        cli: "--cpu-range-batch",
        aliases: &["-Crb"],
        label: "CPU range (batch)",
        description: "Range of CPUs for affinity during batch phase.",
        category: ParamCategory::Threads,
        kind: text_k(""),
    ),
    lp!(
        key: "cpu_strict_batch",
        cli: "--cpu-strict-batch",
        label: "CPU strict (batch)",
        description: "Use strict CPU placement during batch (default: same as --cpu-strict).",
        category: ParamCategory::Threads,
        kind: int(0, 1, 1, 0),
    ),
    lp!(
        key: "prio_batch",
        cli: "--prio-batch",
        label: "Priority (batch)",
        description: "Process/thread priority during batch: 0 normal, 1 medium, 2 high, 3 realtime.",
        category: ParamCategory::Threads,
        kind: int(0, 3, 1, 0),
    ),
    lp!(
        key: "poll_batch",
        cli: "--poll-batch",
        label: "Poll (batch)",
        description: "Polling for batch phase (default: same as --poll).",
        category: ParamCategory::Threads,
        kind: int(0, 1, 1, 0),
    ),

    // ─── Attention / RoPE ─────────────────────────────────────────────────────
    lp!(
        key: "flash_attn",
        cli: "--flash-attn",
        aliases: &["-fa"],
        label: "Flash Attention",
        description: "Set Flash Attention use ('on', 'off', or 'auto', default: 'auto').",
        category: ParamCategory::Attention,
        kind: enum_k(FLASH_ATTN, "auto"),
        env: "LLAMA_ARG_FLASH_ATTN",
    ),
    lp!(
        key: "perf",
        cli: "--perf",
        label: "Perf timings",
        description: "Whether to enable internal libllama performance timings (default: false).",
        category: ParamCategory::Attention,
        kind: bool_k(false),
        env: "LLAMA_ARG_PERF",
    ),
    lp!(
        key: "rope_scaling",
        cli: "--rope-scaling",
        label: "RoPE scaling",
        description: "RoPE frequency scaling method. Defaults to 'linear' unless specified by the model.",
        category: ParamCategory::Attention,
        kind: enum_k(ROPE_SCALING, "linear"),
        env: "LLAMA_ARG_ROPE_SCALING_TYPE",
    ),
    lp!(
        key: "rope_scale",
        cli: "--rope-scale",
        label: "RoPE scale",
        description: "RoPE context scaling factor. Expands context by factor N.",
        category: ParamCategory::Attention,
        kind: float(0.0, 64.0, 0.5, 2, 1.0),
        env: "LLAMA_ARG_ROPE_SCALE",
    ),
    lp!(
        key: "rope_freq_base",
        cli: "--rope-freq-base",
        label: "RoPE freq base",
        description: "RoPE base frequency, used by NTK-aware scaling (default: loaded from model).",
        category: ParamCategory::Attention,
        kind: float(0.0, 10_000_000.0, 1000.0, 1, 10000.0),
        env: "LLAMA_ARG_ROPE_FREQ_BASE",
    ),
    lp!(
        key: "rope_freq_scale",
        cli: "--rope-freq-scale",
        label: "RoPE freq scale",
        description: "RoPE frequency scaling factor. Expands context by factor of 1/N.",
        category: ParamCategory::Attention,
        kind: float(0.0, 64.0, 0.1, 3, 1.0),
        env: "LLAMA_ARG_ROPE_FREQ_SCALE",
    ),
    lp!(
        key: "yarn_orig_ctx",
        cli: "--yarn-orig-ctx",
        label: "YaRN orig ctx",
        description: "YaRN: original context size of model (default: 0 = model training context size).",
        category: ParamCategory::Attention,
        kind: int(0, 1_000_000, 512, 0),
        env: "LLAMA_ARG_YARN_ORIG_CTX",
    ),
    lp!(
        key: "yarn_ext_factor",
        cli: "--yarn-ext-factor",
        label: "YaRN ext factor",
        description: "YaRN: extrapolation mix factor (default: -1.00, 0.0 = full interpolation).",
        category: ParamCategory::Attention,
        kind: float(-1.0, 1.0, 0.05, 2, -1.0),
        env: "LLAMA_ARG_YARN_EXT_FACTOR",
    ),
    lp!(
        key: "yarn_attn_factor",
        cli: "--yarn-attn-factor",
        label: "YaRN attn factor",
        description: "YaRN: scale sqrt(t) or attention magnitude (default: -1.00).",
        category: ParamCategory::Attention,
        kind: float(-1.0, 10.0, 0.1, 2, -1.0),
        env: "LLAMA_ARG_YARN_ATTN_FACTOR",
    ),
    lp!(
        key: "yarn_beta_slow",
        cli: "--yarn-beta-slow",
        label: "YaRN beta slow",
        description: "YaRN: high correction dim or alpha (default: -1.00).",
        category: ParamCategory::Attention,
        kind: float(-1.0, 1000.0, 0.5, 2, -1.0),
        env: "LLAMA_ARG_YARN_BETA_SLOW",
    ),
    lp!(
        key: "yarn_beta_fast",
        cli: "--yarn-beta-fast",
        label: "YaRN beta fast",
        description: "YaRN: low correction dim or beta (default: -1.00).",
        category: ParamCategory::Attention,
        kind: float(-1.0, 1000.0, 0.5, 2, -1.0),
        env: "LLAMA_ARG_YARN_BETA_FAST",
    ),

    // ─── KV cache ────────────────────────────────────────────────────────────
    lp!(
        key: "kv_offload",
        cli: "--kv-offload",
        aliases: &["-kvo", "-nkvo", "--no-kv-offload"],
        label: "KV offload",
        description: "Whether to enable KV cache offloading (default: enabled).",
        category: ParamCategory::KvCache,
        kind: bool_k(true),
        env: "LLAMA_ARG_KV_OFFLOAD",
    ),
    lp!(
        key: "repack",
        cli: "--repack",
        aliases: &["-nr", "--no-repack"],
        label: "Weight repack",
        description: "Whether to enable weight repacking (default: enabled).",
        category: ParamCategory::KvCache,
        kind: bool_k(true),
        env: "LLAMA_ARG_REPACK",
    ),
    lp!(
        key: "no_host",
        cli: "--no-host",
        label: "No host buffer",
        description: "Bypass host buffer allowing extra buffers to be used.",
        category: ParamCategory::KvCache,
        kind: bool_k(false),
        env: "LLAMA_ARG_NO_HOST",
    ),
    lp!(
        key: "cache_type_k",
        cli: "--cache-type-k",
        aliases: &["-ctk"],
        label: "Cache type K",
        description: "KV cache data type for K. Allowed: f32/f16/bf16/q8_0/q4_0/q4_1/iq4_nl/q5_0/q5_1. Default f16.",
        category: ParamCategory::KvCache,
        kind: enum_k(CACHE_TYPES, "f16"),
        env: "LLAMA_ARG_CACHE_TYPE_K",
    ),
    lp!(
        key: "cache_type_v",
        cli: "--cache-type-v",
        aliases: &["-ctv"],
        label: "Cache type V",
        description: "KV cache data type for V. Allowed values same as cache-type-k. Default f16.",
        category: ParamCategory::KvCache,
        kind: enum_k(CACHE_TYPES, "f16"),
        env: "LLAMA_ARG_CACHE_TYPE_V",
    ),
    lp!(
        key: "defrag_thold",
        cli: "--defrag-thold",
        aliases: &["-dt"],
        label: "Defrag thold (DEPRECATED)",
        description: "KV cache defragmentation threshold. DEPRECATED.",
        category: ParamCategory::KvCache,
        kind: float(0.0, 1.0, 0.05, 2, 0.0),
        env: "LLAMA_ARG_DEFRAG_THOLD",
    ),
    lp!(
        key: "cache_type_k_draft",
        cli: "--cache-type-k-draft",
        aliases: &["-ctkd"],
        label: "Cache K (draft)",
        description: "KV cache data type for K for the draft model. Default f16.",
        category: ParamCategory::KvCache,
        kind: enum_k(CACHE_TYPES, "f16"),
        env: "LLAMA_ARG_CACHE_TYPE_K_DRAFT",
    ),
    lp!(
        key: "cache_type_v_draft",
        cli: "--cache-type-v-draft",
        aliases: &["-ctvd"],
        label: "Cache V (draft)",
        description: "KV cache data type for V for the draft model. Default f16.",
        category: ParamCategory::KvCache,
        kind: enum_k(CACHE_TYPES, "f16"),
        env: "LLAMA_ARG_CACHE_TYPE_V_DRAFT",
    ),
    lp!(
        key: "ctx_checkpoints",
        cli: "--ctx-checkpoints",
        aliases: &["-ctxcp", "--swa-checkpoints"],
        label: "Ctx checkpoints",
        description: "Max number of context checkpoints to create per slot (default: 32).",
        category: ParamCategory::KvCache,
        kind: int(0, 10_000, 1, 32),
        env: "LLAMA_ARG_CTX_CHECKPOINTS",
    ),
    lp!(
        key: "checkpoint_every_n_tokens",
        cli: "--checkpoint-every-n-tokens",
        aliases: &["-cpent"],
        label: "Checkpoint every N tokens",
        description: "Create a checkpoint every n tokens during prefill. -1 to disable. Default 8192.",
        category: ParamCategory::KvCache,
        kind: int(-1, 1_000_000, 256, 8192),
        env: "LLAMA_ARG_CHECKPOINT_EVERY_NT",
    ),
    lp!(
        key: "cache_ram",
        cli: "--cache-ram",
        aliases: &["-cram"],
        label: "Cache RAM (MiB)",
        description: "Max cache size in MiB (-1 = no limit, 0 = disable). Default 8192.",
        category: ParamCategory::KvCache,
        kind: int(-1, 1_000_000, 256, 8192),
        env: "LLAMA_ARG_CACHE_RAM",
    ),
    lp!(
        key: "kv_unified",
        cli: "--kv-unified",
        aliases: &["-kvu", "-no-kvu", "--no-kv-unified"],
        label: "KV unified",
        description: "Use single unified KV buffer shared across all sequences.",
        category: ParamCategory::KvCache,
        kind: bool_k(true),
        env: "LLAMA_ARG_KV_UNIFIED",
    ),
    lp!(
        key: "cache_idle_slots",
        cli: "--cache-idle-slots",
        aliases: &["--no-cache-idle-slots"],
        label: "Cache idle slots",
        description: "Save and clear idle slots on new task (requires unified KV and cache-ram).",
        category: ParamCategory::KvCache,
        kind: bool_k(true),
        env: "LLAMA_ARG_CACHE_IDLE_SLOTS",
    ),
    lp!(
        key: "context_shift",
        cli: "--context-shift",
        aliases: &["--no-context-shift"],
        label: "Context shift",
        description: "Whether to use context shift on infinite text generation (default: disabled).",
        category: ParamCategory::KvCache,
        kind: bool_k(false),
        env: "LLAMA_ARG_CONTEXT_SHIFT",
    ),

    // ─── Память / NUMA ───────────────────────────────────────────────────────
    lp!(
        key: "mlock",
        cli: "--mlock",
        label: "mlock",
        description: "Force system to keep model in RAM rather than swapping or compressing.",
        category: ParamCategory::Memory,
        kind: bool_k(false),
        env: "LLAMA_ARG_MLOCK",
    ),
    lp!(
        key: "mmap",
        cli: "--mmap",
        aliases: &["--no-mmap"],
        label: "mmap",
        description: "Memory-map model (if disabled, slower load but reduces pageouts).",
        category: ParamCategory::Memory,
        kind: bool_k(true),
        env: "LLAMA_ARG_MMAP",
    ),
    lp!(
        key: "direct_io",
        cli: "--direct-io",
        aliases: &["-dio", "-ndio", "--no-direct-io"],
        label: "DirectIO",
        description: "Use DirectIO if available (default: disabled).",
        category: ParamCategory::Memory,
        kind: bool_k(false),
        env: "LLAMA_ARG_DIO",
    ),
    lp!(
        key: "numa",
        cli: "--numa",
        label: "NUMA",
        description: "NUMA optimizations: distribute / isolate / numactl.",
        category: ParamCategory::Memory,
        kind: enum_k(NUMA_TYPES, "distribute"),
        env: "LLAMA_ARG_NUMA",
    ),
    lp!(
        key: "rpc",
        cli: "--rpc",
        label: "RPC servers",
        description: "Comma separated list of RPC servers (host:port).",
        category: ParamCategory::Memory,
        kind: text_k(""),
        env: "LLAMA_ARG_RPC",
    ),

    // ─── Устройство / GPU ────────────────────────────────────────────────────
    lp!(
        key: "device",
        cli: "--device",
        aliases: &["-dev"],
        label: "Устройства",
        description: "Comma-separated list of devices for offloading (none = don't offload).",
        category: ParamCategory::Device,
        kind: text_k(""),
        env: "LLAMA_ARG_DEVICE",
    ),
    lp!(
        key: "override_tensor",
        cli: "--override-tensor",
        aliases: &["-ot"],
        label: "Override tensor buffer",
        description: "Override tensor buffer type. Format: <tensor pattern>=<buffer type>,...",
        category: ParamCategory::Device,
        kind: text_k(""),
        env: "LLAMA_ARG_OVERRIDE_TENSOR",
    ),
    lp!(
        key: "cpu_moe",
        cli: "--cpu-moe",
        aliases: &["-cmoe"],
        label: "CPU MoE",
        description: "Keep all Mixture of Experts (MoE) weights in the CPU.",
        category: ParamCategory::Device,
        kind: bool_k(false),
        env: "LLAMA_ARG_CPU_MOE",
    ),
    lp!(
        key: "n_cpu_moe",
        cli: "--n-cpu-moe",
        aliases: &["-ncmoe"],
        label: "N CPU MoE",
        description: "Keep MoE weights of the first N layers in the CPU.",
        category: ParamCategory::Device,
        kind: int(0, 10_000, 1, 0),
        env: "LLAMA_ARG_N_CPU_MOE",
    ),
    lp!(
        key: "gpu_layers",
        cli: "--gpu-layers",
        aliases: &["-ngl", "--n-gpu-layers"],
        label: "GPU layers",
        description: "Max number of layers to store in VRAM: exact number, 'auto', or 'all' (default: auto).",
        category: ParamCategory::Device,
        kind: int(-1, 1000, 1, -1),
        env: "LLAMA_ARG_N_GPU_LAYERS",
    ),
    lp!(
        key: "split_mode",
        cli: "--split-mode",
        aliases: &["-sm"],
        label: "Split mode",
        description: "How to split the model across multiple GPUs. none/layer/row/tensor (experimental).",
        category: ParamCategory::Device,
        kind: enum_k(SPLIT_MODES, "layer"),
        env: "LLAMA_ARG_SPLIT_MODE",
    ),
    lp!(
        key: "tensor_split",
        cli: "--tensor-split",
        aliases: &["-ts"],
        label: "Tensor split",
        description: "Fraction of the model to offload to each GPU, comma-separated, e.g. 3,1.",
        category: ParamCategory::Device,
        kind: text_k(""),
        env: "LLAMA_ARG_TENSOR_SPLIT",
    ),
    lp!(
        key: "main_gpu",
        cli: "--main-gpu",
        aliases: &["-mg"],
        label: "Main GPU",
        description: "The GPU to use (with split-mode=none), or for intermediate results / KV (with split-mode=row).",
        category: ParamCategory::Device,
        kind: int(0, 32, 1, 0),
        env: "LLAMA_ARG_MAIN_GPU",
    ),
    lp!(
        key: "fit",
        cli: "--fit",
        aliases: &["-fit"],
        label: "Auto-fit memory",
        description: "Whether to adjust unset arguments to fit in device memory (default: on).",
        category: ParamCategory::Device,
        kind: bool_k(true),
        env: "LLAMA_ARG_FIT",
    ),
    lp!(
        key: "fit_target",
        cli: "--fit-target",
        aliases: &["-fitt"],
        label: "Fit target (MiB)",
        description: "Target margin per device for --fit, MiB. Comma-separated; single value broadcasts. Default 1024.",
        category: ParamCategory::Device,
        kind: text_k("1024"),
        env: "LLAMA_ARG_FIT_TARGET",
    ),
    lp!(
        key: "fit_ctx",
        cli: "--fit-ctx",
        aliases: &["-fitc"],
        label: "Fit min ctx",
        description: "Minimum ctx size that can be set by --fit. Default 4096.",
        category: ParamCategory::Device,
        kind: int(256, 1_000_000, 256, 4096),
        env: "LLAMA_ARG_FIT_CTX",
    ),
    lp!(
        key: "check_tensors",
        cli: "--check-tensors",
        label: "Check tensors",
        description: "Check model tensor data for invalid values (default: false).",
        category: ParamCategory::Device,
        kind: bool_k(false),
    ),
    lp!(
        key: "override_kv",
        cli: "--override-kv",
        label: "Override KV metadata",
        description: "Advanced: override model metadata by key. KEY=TYPE:VALUE,... Types: int/float/bool/str.",
        category: ParamCategory::Device,
        kind: text_k(""),
    ),
    lp!(
        key: "op_offload",
        cli: "--op-offload",
        aliases: &["--no-op-offload"],
        label: "Op offload",
        description: "Offload host tensor operations to device (default: true).",
        category: ParamCategory::Device,
        kind: bool_k(true),
    ),

    // ─── Загрузка модели / HF / LoRA ─────────────────────────────────────────
    lp!(
        key: "model",
        cli: "--model",
        aliases: &["-m"],
        label: "Model path",
        description: "Путь к модели (.gguf). Задаётся отдельно от чипов — в поле «Путь к модели».",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_MODEL",
    ),
    lp!(
        key: "model_url",
        cli: "--model-url",
        aliases: &["-mu"],
        label: "Model URL",
        description: "URL для скачивания модели (default: unused).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_MODEL_URL",
    ),
    lp!(
        key: "docker_repo",
        cli: "--docker-repo",
        aliases: &["-dr"],
        label: "Docker repo",
        description: "Docker Hub model repository. repo optional (default 'ai/'), quant optional (':latest').",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_DOCKER_REPO",
    ),
    lp!(
        key: "hf_repo",
        cli: "--hf-repo",
        aliases: &["-hf", "-hfr"],
        label: "HF repo",
        description: "Hugging Face model repository <user>/<model>[:quant]. Default Q4_K_M.",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_HF_REPO",
    ),
    lp!(
        key: "hf_repo_draft",
        cli: "--hf-repo-draft",
        aliases: &["-hfd", "-hfrd"],
        label: "HF repo (draft)",
        description: "Same as --hf-repo, but for the draft model.",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_HFD_REPO",
    ),
    lp!(
        key: "hf_file",
        cli: "--hf-file",
        aliases: &["-hff"],
        label: "HF file",
        description: "Конкретный файл из HF-репо (переопределяет quant из --hf-repo).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_HF_FILE",
    ),
    lp!(
        key: "hf_repo_v",
        cli: "--hf-repo-v",
        aliases: &["-hfv", "-hfrv"],
        label: "HF repo (vocoder)",
        description: "Hugging Face repo for vocoder model.",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_HF_REPO_V",
    ),
    lp!(
        key: "hf_file_v",
        cli: "--hf-file-v",
        aliases: &["-hffv"],
        label: "HF file (vocoder)",
        description: "HF model file for vocoder.",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "LLAMA_ARG_HF_FILE_V",
    ),
    lp!(
        key: "hf_token",
        cli: "--hf-token",
        aliases: &["-hft"],
        label: "HF token",
        description: "Hugging Face access token (default: from HF_TOKEN env).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
        env: "HF_TOKEN",
    ),
    lp!(
        key: "lora",
        cli: "--lora",
        label: "LoRA adapter",
        description: "Path to LoRA adapter (comma-separated to load multiple).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
    ),
    lp!(
        key: "lora_scaled",
        cli: "--lora-scaled",
        label: "LoRA scaled",
        description: "LoRA adapter with user-defined scaling (FNAME:SCALE,...).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
    ),
    lp!(
        key: "control_vector",
        cli: "--control-vector",
        label: "Control vector",
        description: "Add a control vector (comma-separated to add multiple).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
    ),
    lp!(
        key: "control_vector_scaled",
        cli: "--control-vector-scaled",
        label: "Control vector scaled",
        description: "Control vector with user-defined scaling (FNAME:SCALE,...).",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
    ),
    lp!(
        key: "control_vector_layer_range",
        cli: "--control-vector-layer-range",
        label: "Control vector layer range",
        description: "Layer range (START END) to apply control vectors. Both inclusive.",
        category: ParamCategory::ModelLoading,
        kind: text_k(""),
    ),

    // ─── Logging ─────────────────────────────────────────────────────────────
    lp!(
        key: "log_disable",
        cli: "--log-disable",
        label: "Log disable",
        description: "Disable logging entirely.",
        category: ParamCategory::Logging,
        kind: bool_k(false),
    ),
    lp!(
        key: "log_file",
        cli: "--log-file",
        label: "Log to file",
        description: "Log to FNAME.",
        category: ParamCategory::Logging,
        kind: text_k(""),
        env: "LLAMA_LOG_FILE",
    ),
    lp!(
        key: "log_colors",
        cli: "--log-colors",
        label: "Log colors",
        description: "Colored logging: auto (default), on, off.",
        category: ParamCategory::Logging,
        kind: enum_k(LOG_COLORS, "auto"),
        env: "LLAMA_LOG_COLORS",
    ),
    lp!(
        key: "verbose",
        cli: "--verbose",
        aliases: &["-v", "--log-verbose"],
        label: "Verbose",
        description: "Set verbosity level to infinity (log all messages).",
        category: ParamCategory::Logging,
        kind: bool_k(false),
    ),
    lp!(
        key: "offline",
        cli: "--offline",
        label: "Offline mode",
        description: "Force use of cache, prevent network access.",
        category: ParamCategory::Logging,
        kind: bool_k(false),
        env: "LLAMA_OFFLINE",
    ),
    lp!(
        key: "verbosity",
        cli: "--verbosity",
        aliases: &["-lv", "--log-verbosity"],
        label: "Verbosity level",
        description: "0 output, 1 error, 2 warning, 3 info (default), 4 debug.",
        category: ParamCategory::Logging,
        kind: int(0, 4, 1, 3),
        env: "LLAMA_LOG_VERBOSITY",
    ),
    lp!(
        key: "log_prefix",
        cli: "--log-prefix",
        label: "Log prefix",
        description: "Enable prefix in log messages.",
        category: ParamCategory::Logging,
        kind: bool_k(false),
        env: "LLAMA_LOG_PREFIX",
    ),
    lp!(
        key: "log_timestamps",
        cli: "--log-timestamps",
        label: "Log timestamps",
        description: "Enable timestamps in log messages.",
        category: ParamCategory::Logging,
        kind: bool_k(false),
        env: "LLAMA_LOG_TIMESTAMPS",
    ),

    // ─── Sampling ────────────────────────────────────────────────────────────
    lp!(
        key: "samplers",
        cli: "--samplers",
        label: "Samplers",
        description: "Samplers for generation in order, separated by ';'.",
        category: ParamCategory::Sampling,
        kind: text_k("penalties;dry;top_n_sigma;top_k;typ_p;top_p;min_p;xtc;temperature"),
    ),
    lp!(
        key: "seed",
        cli: "--seed",
        aliases: &["-s"],
        label: "Seed",
        description: "RNG seed (default: -1 = random).",
        category: ParamCategory::Sampling,
        kind: int(-1, i64::MAX, 1, -1),
    ),
    lp!(
        key: "sampler_seq",
        cli: "--sampler-seq",
        aliases: &["--sampling-seq"],
        label: "Sampler sequence",
        description: "Simplified sampler sequence (default: edskypmxt).",
        category: ParamCategory::Sampling,
        kind: text_k("edskypmxt"),
    ),
    lp!(
        key: "ignore_eos",
        cli: "--ignore-eos",
        label: "Ignore EOS",
        description: "Ignore end of stream token (implies --logit-bias EOS-inf).",
        category: ParamCategory::Sampling,
        kind: bool_k(false),
    ),
    lp!(
        key: "temperature",
        cli: "--temp",
        aliases: &["--temperature"],
        label: "Температура",
        description: "Temperature for sampling (default: 0.80).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 5.0, 0.05, 2, 0.8),
    ),
    lp!(
        key: "top_k",
        cli: "--top-k",
        label: "Top-K",
        description: "Top-K sampling (default: 40, 0 = disabled).",
        category: ParamCategory::Sampling,
        kind: int(0, 10_000, 1, 40),
        env: "LLAMA_ARG_TOP_K",
    ),
    lp!(
        key: "top_p",
        cli: "--top-p",
        label: "Top-P",
        description: "Top-P sampling (default: 0.95, 1.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 1.0, 0.01, 3, 0.95),
    ),
    lp!(
        key: "min_p",
        cli: "--min-p",
        label: "Min-P",
        description: "Min-P sampling (default: 0.05, 0.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 1.0, 0.01, 3, 0.05),
    ),
    lp!(
        key: "top_nsigma",
        cli: "--top-nsigma",
        aliases: &["--top-n-sigma"],
        label: "Top-N-Sigma",
        description: "Top-N-Sigma sampling (default: -1.00, -1.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(-1.0, 10.0, 0.1, 2, -1.0),
    ),
    lp!(
        key: "xtc_probability",
        cli: "--xtc-probability",
        label: "XTC probability",
        description: "XTC probability (default: 0.00, 0.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 1.0, 0.01, 2, 0.0),
    ),
    lp!(
        key: "xtc_threshold",
        cli: "--xtc-threshold",
        label: "XTC threshold",
        description: "XTC threshold (default: 0.10, 1.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 1.0, 0.01, 2, 0.1),
    ),
    lp!(
        key: "typical",
        cli: "--typical",
        aliases: &["--typical-p"],
        label: "Typical-P",
        description: "Locally typical sampling p (default: 1.00, 1.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 1.0, 0.01, 2, 1.0),
    ),
    lp!(
        key: "repeat_last_n",
        cli: "--repeat-last-n",
        label: "Repeat last N",
        description: "Last n tokens to penalize (default: 64, 0 = disabled, -1 = ctx_size).",
        category: ParamCategory::Sampling,
        kind: int(-1, 100_000, 8, 64),
    ),
    lp!(
        key: "repeat_penalty",
        cli: "--repeat-penalty",
        label: "Repeat penalty",
        description: "Penalize repeat sequence of tokens (default: 1.00, 1.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 2.0, 0.01, 2, 1.0),
    ),
    lp!(
        key: "presence_penalty",
        cli: "--presence-penalty",
        label: "Presence penalty",
        description: "Repeat alpha presence penalty (default: 0.00).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 2.0, 0.01, 2, 0.0),
    ),
    lp!(
        key: "frequency_penalty",
        cli: "--frequency-penalty",
        label: "Frequency penalty",
        description: "Repeat alpha frequency penalty (default: 0.00).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 2.0, 0.01, 2, 0.0),
    ),
    lp!(
        key: "dry_multiplier",
        cli: "--dry-multiplier",
        label: "DRY multiplier",
        description: "DRY sampling multiplier (default: 0.00, 0.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 10.0, 0.05, 2, 0.0),
    ),
    lp!(
        key: "dry_base",
        cli: "--dry-base",
        label: "DRY base",
        description: "DRY sampling base value (default: 1.75).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 10.0, 0.05, 2, 1.75),
    ),
    lp!(
        key: "dry_allowed_length",
        cli: "--dry-allowed-length",
        label: "DRY allowed length",
        description: "Allowed length for DRY sampling (default: 2).",
        category: ParamCategory::Sampling,
        kind: int(0, 1000, 1, 2),
    ),
    lp!(
        key: "dry_penalty_last_n",
        cli: "--dry-penalty-last-n",
        label: "DRY penalty last N",
        description: "DRY penalty for last n tokens (default: -1, 0 = disable, -1 = ctx).",
        category: ParamCategory::Sampling,
        kind: int(-1, 100_000, 8, -1),
    ),
    lp!(
        key: "dry_sequence_breaker",
        cli: "--dry-sequence-breaker",
        label: "DRY sequence breaker",
        description: "Add sequence breaker for DRY. Default breakers cleared on first use. 'none' disables.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "adaptive_target",
        cli: "--adaptive-target",
        label: "Adaptive target",
        description: "Adaptive-p: select tokens near this probability (0.0–1.0, negative = disabled). Default -1.",
        category: ParamCategory::Sampling,
        kind: float(-1.0, 1.0, 0.01, 3, -1.0),
    ),
    lp!(
        key: "adaptive_decay",
        cli: "--adaptive-decay",
        label: "Adaptive decay",
        description: "Adaptive-p: decay rate (0.0–0.99). Lower = more reactive. Default 0.90.",
        category: ParamCategory::Sampling,
        kind: float(0.0, 0.99, 0.01, 2, 0.9),
    ),
    lp!(
        key: "dynatemp_range",
        cli: "--dynatemp-range",
        label: "Dynamic temp range",
        description: "Dynamic temperature range (default: 0.00, 0.0 = disabled).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 5.0, 0.05, 2, 0.0),
    ),
    lp!(
        key: "dynatemp_exp",
        cli: "--dynatemp-exp",
        label: "Dynamic temp exponent",
        description: "Dynamic temperature exponent (default: 1.00).",
        category: ParamCategory::Sampling,
        kind: float(0.0, 10.0, 0.05, 2, 1.0),
    ),
    lp!(
        key: "mirostat",
        cli: "--mirostat",
        label: "Mirostat",
        description: "Mirostat sampling (0 = disabled, 1 = v1, 2 = v2.0). Ignores Top-K/Nucleus/Typical.",
        category: ParamCategory::Sampling,
        kind: int(0, 2, 1, 0),
    ),
    lp!(
        key: "mirostat_lr",
        cli: "--mirostat-lr",
        label: "Mirostat LR",
        description: "Mirostat learning rate (eta). Default 0.10.",
        category: ParamCategory::Sampling,
        kind: float(0.0, 5.0, 0.01, 2, 0.1),
    ),
    lp!(
        key: "mirostat_ent",
        cli: "--mirostat-ent",
        label: "Mirostat entropy",
        description: "Mirostat target entropy (tau). Default 5.00.",
        category: ParamCategory::Sampling,
        kind: float(0.0, 20.0, 0.5, 2, 5.0),
    ),
    lp!(
        key: "logit_bias",
        cli: "--logit-bias",
        aliases: &["-l"],
        label: "Logit bias",
        description: "TOKEN_ID(+/-)BIAS. Например `15043+1` повышает, `15043-1` понижает likelihood.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "grammar",
        cli: "--grammar",
        label: "Grammar",
        description: "BNF-like grammar to constrain generations.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "grammar_file",
        cli: "--grammar-file",
        label: "Grammar file",
        description: "Файл с грамматикой.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "json_schema",
        cli: "--json-schema",
        aliases: &["-j"],
        label: "JSON schema",
        description: "JSON schema для ограничения генерации. `{}` = любой JSON.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "json_schema_file",
        cli: "--json-schema-file",
        aliases: &["-jf"],
        label: "JSON schema file",
        description: "Файл с JSON schema.",
        category: ParamCategory::Sampling,
        kind: text_k(""),
    ),
    lp!(
        key: "backend_sampling",
        cli: "--backend-sampling",
        aliases: &["-bs"],
        label: "Backend sampling",
        description: "Enable backend sampling (experimental). Default disabled.",
        category: ParamCategory::Sampling,
        kind: bool_k(false),
        env: "LLAMA_ARG_BACKEND_SAMPLING",
    ),

    // ─── Сервер ──────────────────────────────────────────────────────────────
    lp!(
        key: "host",
        cli: "--host",
        label: "Host",
        description: "IP to listen on (or UNIX socket at .sock). Default 127.0.0.1.",
        category: ParamCategory::Server,
        kind: text_k("127.0.0.1"),
        env: "LLAMA_ARG_HOST",
    ),
    lp!(
        key: "port",
        cli: "--port",
        label: "Port",
        description: "Port to listen on (default: 8080).",
        category: ParamCategory::Server,
        kind: int(1, 65535, 1, 8080),
        env: "LLAMA_ARG_PORT",
    ),
    lp!(
        key: "reuse_port",
        cli: "--reuse-port",
        label: "Reuse port",
        description: "Allow multiple sockets to bind to the same port.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_REUSE_PORT",
    ),
    lp!(
        key: "path",
        cli: "--path",
        label: "Static path",
        description: "Path to serve static files from.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_STATIC_PATH",
    ),
    lp!(
        key: "api_prefix",
        cli: "--api-prefix",
        label: "API prefix",
        description: "Prefix path the server serves from, without trailing slash.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_API_PREFIX",
    ),
    lp!(
        key: "webui_config",
        cli: "--webui-config",
        label: "WebUI config JSON",
        description: "JSON with default WebUI settings (overrides defaults).",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_WEBUI_CONFIG",
    ),
    lp!(
        key: "webui_config_file",
        cli: "--webui-config-file",
        label: "WebUI config file",
        description: "JSON file with WebUI default settings.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_WEBUI_CONFIG_FILE",
    ),
    lp!(
        key: "webui_mcp_proxy",
        cli: "--webui-mcp-proxy",
        aliases: &["--no-webui-mcp-proxy"],
        label: "WebUI MCP proxy",
        description: "Experimental: enable MCP CORS proxy. Do not enable in untrusted envs.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_WEBUI_MCP_PROXY",
    ),
    lp!(
        key: "tools",
        cli: "--tools",
        label: "Built-in tools",
        description: "Experimental: enable built-in tools (read_file, file_glob_search, grep_search, exec_shell_command, write_file, edit_file, apply_diff). 'all' = all.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_TOOLS",
    ),
    lp!(
        key: "webui",
        cli: "--webui",
        aliases: &["--no-webui"],
        label: "Web UI",
        description: "Enable Web UI (default: enabled).",
        category: ParamCategory::Server,
        kind: bool_k(true),
        env: "LLAMA_ARG_WEBUI",
    ),
    lp!(
        key: "embedding",
        cli: "--embedding",
        aliases: &["--embeddings"],
        label: "Embedding only",
        description: "Restrict to embedding use case only.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_EMBEDDINGS",
    ),
    lp!(
        key: "rerank",
        cli: "--rerank",
        aliases: &["--reranking"],
        label: "Reranking",
        description: "Enable reranking endpoint.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_RERANKING",
    ),
    lp!(
        key: "api_key",
        cli: "--api-key",
        label: "API key",
        description: "API key(s) for authentication, comma-separated.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_API_KEY",
    ),
    lp!(
        key: "api_key_file",
        cli: "--api-key-file",
        label: "API key file",
        description: "Path to file with API keys.",
        category: ParamCategory::Server,
        kind: text_k(""),
    ),
    lp!(
        key: "ssl_key_file",
        cli: "--ssl-key-file",
        label: "SSL key file",
        description: "Path to PEM-encoded SSL private key.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_SSL_KEY_FILE",
    ),
    lp!(
        key: "ssl_cert_file",
        cli: "--ssl-cert-file",
        label: "SSL cert file",
        description: "Path to PEM-encoded SSL certificate.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_SSL_CERT_FILE",
    ),
    lp!(
        key: "chat_template_kwargs",
        cli: "--chat-template-kwargs",
        label: "Chat template kwargs",
        description: "JSON object string with additional params for chat template parser.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_CHAT_TEMPLATE_KWARGS",
    ),
    lp!(
        key: "timeout",
        cli: "--timeout",
        aliases: &["-to"],
        label: "Timeout (sec)",
        description: "Server read/write timeout in seconds. Default 600.",
        category: ParamCategory::Server,
        kind: int(0, 86400, 30, 600),
        env: "LLAMA_ARG_TIMEOUT",
    ),
    lp!(
        key: "threads_http",
        cli: "--threads-http",
        label: "HTTP threads",
        description: "Number of threads for HTTP requests. Default -1.",
        category: ParamCategory::Server,
        kind: int(-1, 1024, 1, -1),
        env: "LLAMA_ARG_THREADS_HTTP",
    ),
    lp!(
        key: "cache_prompt",
        cli: "--cache-prompt",
        aliases: &["--no-cache-prompt"],
        label: "Cache prompt",
        description: "Prompt caching (default: enabled).",
        category: ParamCategory::Server,
        kind: bool_k(true),
        env: "LLAMA_ARG_CACHE_PROMPT",
    ),
    lp!(
        key: "cache_reuse",
        cli: "--cache-reuse",
        label: "Cache reuse",
        description: "Min chunk size to reuse from cache via KV shifting. Requires prompt caching. Default 0.",
        category: ParamCategory::Server,
        kind: int(0, 100_000, 16, 0),
        env: "LLAMA_ARG_CACHE_REUSE",
    ),
    lp!(
        key: "metrics",
        cli: "--metrics",
        label: "Prometheus metrics",
        description: "Enable Prometheus-compatible metrics endpoint.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_ENDPOINT_METRICS",
    ),
    lp!(
        key: "props",
        cli: "--props",
        label: "Endpoint /props",
        description: "Enable changing global properties via POST /props.",
        category: ParamCategory::Server,
        kind: bool_k(false),
        env: "LLAMA_ARG_ENDPOINT_PROPS",
    ),
    lp!(
        key: "slots",
        cli: "--slots",
        aliases: &["--no-slots"],
        label: "Slots endpoint",
        description: "Expose slots monitoring endpoint.",
        category: ParamCategory::Server,
        kind: bool_k(true),
        env: "LLAMA_ARG_ENDPOINT_SLOTS",
    ),
    lp!(
        key: "slot_save_path",
        cli: "--slot-save-path",
        label: "Slot save path",
        description: "Path to save slot KV cache.",
        category: ParamCategory::Server,
        kind: text_k(""),
    ),
    lp!(
        key: "media_path",
        cli: "--media-path",
        label: "Media path",
        description: "Directory for local media files (accessed via file:// URLs).",
        category: ParamCategory::Server,
        kind: text_k(""),
    ),
    lp!(
        key: "models_dir",
        cli: "--models-dir",
        label: "Models dir",
        description: "Directory with models for router server.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_MODELS_DIR",
    ),
    lp!(
        key: "models_preset",
        cli: "--models-preset",
        label: "Models preset",
        description: "INI file with model presets for router server.",
        category: ParamCategory::Server,
        kind: text_k(""),
        env: "LLAMA_ARG_MODELS_PRESET",
    ),
    lp!(
        key: "models_max",
        cli: "--models-max",
        label: "Models max",
        description: "Router: max simultaneously loaded models (0 = unlimited). Default 4.",
        category: ParamCategory::Server,
        kind: int(0, 1000, 1, 4),
        env: "LLAMA_ARG_MODELS_MAX",
    ),
    lp!(
        key: "models_autoload",
        cli: "--models-autoload",
        aliases: &["--no-models-autoload"],
        label: "Models autoload",
        description: "Router: automatically load models (default: enabled).",
        category: ParamCategory::Server,
        kind: bool_k(true),
        env: "LLAMA_ARG_MODELS_AUTOLOAD",
    ),

    // ─── Chat template / Reasoning / Jinja ──────────────────────────────────
    lp!(
        key: "jinja",
        cli: "--jinja",
        aliases: &["--no-jinja"],
        label: "Jinja engine",
        description: "Use jinja template engine for chat (default: enabled).",
        category: ParamCategory::ChatTemplate,
        kind: bool_k(true),
        env: "LLAMA_ARG_JINJA",
    ),
    lp!(
        key: "reasoning_format",
        cli: "--reasoning-format",
        label: "Reasoning format",
        description: "Как возвращать thought tags: auto / none / deepseek / deepseek-legacy.",
        category: ParamCategory::ChatTemplate,
        kind: enum_k(REASONING_FORMATS, "auto"),
        env: "LLAMA_ARG_THINK",
    ),
    lp!(
        key: "reasoning",
        cli: "--reasoning",
        aliases: &["-rea"],
        label: "Reasoning",
        description: "Use reasoning/thinking in chat: on / off / auto.",
        category: ParamCategory::ChatTemplate,
        kind: enum_k(REASONING_MODES, "auto"),
        env: "LLAMA_ARG_REASONING",
    ),
    lp!(
        key: "reasoning_budget",
        cli: "--reasoning-budget",
        label: "Reasoning budget",
        description: "Token budget for thinking (-1 unrestricted, 0 immediate end).",
        category: ParamCategory::ChatTemplate,
        kind: int(-1, 1_000_000, 64, -1),
        env: "LLAMA_ARG_THINK_BUDGET",
    ),
    lp!(
        key: "reasoning_budget_message",
        cli: "--reasoning-budget-message",
        label: "Reasoning budget message",
        description: "Message injected before end-of-thinking when budget exhausted.",
        category: ParamCategory::ChatTemplate,
        kind: text_k(""),
        env: "LLAMA_ARG_THINK_BUDGET_MESSAGE",
    ),
    lp!(
        key: "chat_template",
        cli: "--chat-template",
        label: "Chat template",
        description: "Custom jinja chat template name or content. См. встроенные шаблоны в docs.",
        category: ParamCategory::ChatTemplate,
        kind: enum_k(CHAT_TEMPLATES, "llama3"),
        env: "LLAMA_ARG_CHAT_TEMPLATE",
    ),
    lp!(
        key: "chat_template_file",
        cli: "--chat-template-file",
        label: "Chat template file",
        description: "Файл с jinja-шаблоном.",
        category: ParamCategory::ChatTemplate,
        kind: text_k(""),
        env: "LLAMA_ARG_CHAT_TEMPLATE_FILE",
    ),
    lp!(
        key: "skip_chat_parsing",
        cli: "--skip-chat-parsing",
        aliases: &["--no-skip-chat-parsing"],
        label: "Skip chat parsing",
        description: "Force pure content parser, even with Jinja template.",
        category: ParamCategory::ChatTemplate,
        kind: bool_k(false),
        env: "LLAMA_ARG_SKIP_CHAT_PARSING",
    ),
    lp!(
        key: "prefill_assistant",
        cli: "--prefill-assistant",
        aliases: &["--no-prefill-assistant"],
        label: "Prefill assistant",
        description: "Prefill the assistant's response if last message is from assistant (default enabled).",
        category: ParamCategory::ChatTemplate,
        kind: bool_k(true),
        env: "LLAMA_ARG_PREFILL_ASSISTANT",
    ),
    lp!(
        key: "slot_prompt_similarity",
        cli: "--slot-prompt-similarity",
        aliases: &["-sps"],
        label: "Slot prompt similarity",
        description: "Required similarity between request prompt and slot prompt (default: 0.10, 0.0 = disabled).",
        category: ParamCategory::ChatTemplate,
        kind: float(0.0, 1.0, 0.01, 2, 0.1),
    ),
    lp!(
        key: "lora_init_without_apply",
        cli: "--lora-init-without-apply",
        label: "LoRA init w/o apply",
        description: "Load LoRA adapters without applying; apply later via POST /lora-adapters.",
        category: ParamCategory::ChatTemplate,
        kind: bool_k(false),
    ),
    lp!(
        key: "sleep_idle_seconds",
        cli: "--sleep-idle-seconds",
        label: "Sleep idle (sec)",
        description: "Seconds of idleness before the server sleeps. -1 = disabled.",
        category: ParamCategory::ChatTemplate,
        kind: int(-1, 86400, 10, -1),
    ),
    lp!(
        key: "alias",
        cli: "--alias",
        aliases: &["-a"],
        label: "Aliases",
        description: "Model name aliases, comma-separated (used by API).",
        category: ParamCategory::ChatTemplate,
        kind: text_k(""),
        env: "LLAMA_ARG_ALIAS",
    ),
    lp!(
        key: "tags",
        cli: "--tags",
        label: "Tags",
        description: "Model tags, comma-separated (informational).",
        category: ParamCategory::ChatTemplate,
        kind: text_k(""),
        env: "LLAMA_ARG_TAGS",
    ),

    // ─── Multimodal / vision ─────────────────────────────────────────────────
    lp!(
        key: "mmproj",
        cli: "--mmproj",
        aliases: &["-mm"],
        label: "mmproj",
        description: "Путь к multimodal projector. Задаётся отдельно в поле «Путь к mmproj».",
        category: ParamCategory::Multimodal,
        kind: text_k(""),
        env: "LLAMA_ARG_MMPROJ",
    ),
    lp!(
        key: "mmproj_url",
        cli: "--mmproj-url",
        aliases: &["-mmu"],
        label: "mmproj URL",
        description: "URL к mmproj-файлу.",
        category: ParamCategory::Multimodal,
        kind: text_k(""),
        env: "LLAMA_ARG_MMPROJ_URL",
    ),
    lp!(
        key: "mmproj_auto",
        cli: "--mmproj-auto",
        aliases: &["--no-mmproj", "--no-mmproj-auto"],
        label: "mmproj auto",
        description: "Use multimodal projector file if available (default: enabled).",
        category: ParamCategory::Multimodal,
        kind: bool_k(true),
        env: "LLAMA_ARG_MMPROJ_AUTO",
    ),
    lp!(
        key: "mmproj_offload",
        cli: "--mmproj-offload",
        aliases: &["--no-mmproj-offload"],
        label: "mmproj offload",
        description: "GPU offloading for multimodal projector (default: enabled).",
        category: ParamCategory::Multimodal,
        kind: bool_k(true),
        env: "LLAMA_ARG_MMPROJ_OFFLOAD",
    ),
    lp!(
        key: "image_min_tokens",
        cli: "--image-min-tokens",
        label: "Image min tokens",
        description: "Min tokens per image (dynamic resolution vision).",
        category: ParamCategory::Multimodal,
        kind: int(0, 100_000, 16, 0),
        env: "LLAMA_ARG_IMAGE_MIN_TOKENS",
    ),
    lp!(
        key: "image_max_tokens",
        cli: "--image-max-tokens",
        label: "Image max tokens",
        description: "Max tokens per image (dynamic resolution vision).",
        category: ParamCategory::Multimodal,
        kind: int(0, 1_000_000, 32, 0),
        env: "LLAMA_ARG_IMAGE_MAX_TOKENS",
    ),

    // ─── Параллелизм ────────────────────────────────────────────────────────
    lp!(
        key: "parallel",
        cli: "--parallel",
        aliases: &["-np"],
        label: "Server slots",
        description: "Number of server slots (default: -1 = auto).",
        category: ParamCategory::Parallelism,
        kind: int(-1, 256, 1, -1),
        env: "LLAMA_ARG_N_PARALLEL",
    ),
    lp!(
        key: "cont_batching",
        cli: "--cont-batching",
        aliases: &["-cb", "-nocb", "--no-cont-batching"],
        label: "Continuous batching",
        description: "Continuous (dynamic) batching (default: enabled).",
        category: ParamCategory::Parallelism,
        kind: bool_k(true),
        env: "LLAMA_ARG_CONT_BATCHING",
    ),

    // ─── Speculative decoding ────────────────────────────────────────────────
    lp!(
        key: "override_tensor_draft",
        cli: "--override-tensor-draft",
        aliases: &["-otd"],
        label: "Override tensor (draft)",
        description: "Override tensor buffer type for draft model.",
        category: ParamCategory::Speculative,
        kind: text_k(""),
    ),
    lp!(
        key: "cpu_moe_draft",
        cli: "--cpu-moe-draft",
        aliases: &["-cmoed"],
        label: "CPU MoE (draft)",
        description: "Keep MoE weights of draft model in CPU.",
        category: ParamCategory::Speculative,
        kind: bool_k(false),
        env: "LLAMA_ARG_CPU_MOE_DRAFT",
    ),
    lp!(
        key: "n_cpu_moe_draft",
        cli: "--n-cpu-moe-draft",
        aliases: &["-ncmoed"],
        label: "N CPU MoE (draft)",
        description: "Keep MoE weights of first N layers of draft model in CPU.",
        category: ParamCategory::Speculative,
        kind: int(0, 10_000, 1, 0),
        env: "LLAMA_ARG_N_CPU_MOE_DRAFT",
    ),
    lp!(
        key: "threads_draft",
        cli: "--threads-draft",
        aliases: &["-td"],
        label: "Threads (draft)",
        description: "Threads for draft generation. Default same as --threads.",
        category: ParamCategory::Speculative,
        kind: int(-1, 256, 1, -1),
    ),
    lp!(
        key: "threads_batch_draft",
        cli: "--threads-batch-draft",
        aliases: &["-tbd"],
        label: "Threads batch (draft)",
        description: "Threads for batch draft. Default same as --threads-draft.",
        category: ParamCategory::Speculative,
        kind: int(-1, 256, 1, -1),
    ),
    lp!(
        key: "draft_max",
        cli: "--draft",
        aliases: &["--draft-n", "--draft-max"],
        label: "Draft max",
        description: "Number of tokens to draft for speculative decoding (default: 16).",
        category: ParamCategory::Speculative,
        kind: int(0, 1024, 1, 16),
        env: "LLAMA_ARG_DRAFT_MAX",
    ),
    lp!(
        key: "draft_min",
        cli: "--draft-min",
        aliases: &["--draft-n-min"],
        label: "Draft min",
        description: "Minimum number of draft tokens (default: 0).",
        category: ParamCategory::Speculative,
        kind: int(0, 1024, 1, 0),
        env: "LLAMA_ARG_DRAFT_MIN",
    ),
    lp!(
        key: "draft_p_min",
        cli: "--draft-p-min",
        label: "Draft p-min",
        description: "Minimum speculative decoding probability (greedy). Default 0.75.",
        category: ParamCategory::Speculative,
        kind: float(0.0, 1.0, 0.01, 2, 0.75),
        env: "LLAMA_ARG_DRAFT_P_MIN",
    ),
    lp!(
        key: "ctx_size_draft",
        cli: "--ctx-size-draft",
        aliases: &["-cd"],
        label: "Ctx size (draft)",
        description: "Size of prompt context for draft model (default: 0, 0 = loaded from model).",
        category: ParamCategory::Speculative,
        kind: int(0, 1_000_000, 512, 0),
        env: "LLAMA_ARG_CTX_SIZE_DRAFT",
    ),
    lp!(
        key: "device_draft",
        cli: "--device-draft",
        aliases: &["-devd"],
        label: "Device (draft)",
        description: "Devices for offload of draft model (none = no offload).",
        category: ParamCategory::Speculative,
        kind: text_k(""),
    ),
    lp!(
        key: "gpu_layers_draft",
        cli: "--gpu-layers-draft",
        aliases: &["-ngld", "--n-gpu-layers-draft"],
        label: "GPU layers (draft)",
        description: "Layers of draft model in VRAM (default: auto).",
        category: ParamCategory::Speculative,
        kind: int(-1, 1000, 1, -1),
        env: "LLAMA_ARG_N_GPU_LAYERS_DRAFT",
    ),
    lp!(
        key: "model_draft",
        cli: "--model-draft",
        aliases: &["-md"],
        label: "Model (draft)",
        description: "Draft model for speculative decoding.",
        category: ParamCategory::Speculative,
        kind: text_k(""),
        env: "LLAMA_ARG_MODEL_DRAFT",
    ),
    lp!(
        key: "spec_replace",
        cli: "--spec-replace",
        label: "Spec replace",
        description: "Translate TARGET string into DRAFT if draft and main model are not compatible.",
        category: ParamCategory::Speculative,
        kind: text_k(""),
    ),
    lp!(
        key: "spec_type",
        cli: "--spec-type",
        label: "Spec type",
        description: "Speculative decoding type when no draft model provided.",
        category: ParamCategory::Speculative,
        kind: enum_k(SPEC_TYPES, "none"),
        env: "LLAMA_ARG_SPEC_TYPE",
    ),
    lp!(
        key: "spec_ngram_size_n",
        cli: "--spec-ngram-size-n",
        label: "Spec ngram size N",
        description: "Lookup n-gram length for ngram-simple / ngram-map (default: 12).",
        category: ParamCategory::Speculative,
        kind: int(1, 100, 1, 12),
    ),
    lp!(
        key: "spec_ngram_size_m",
        cli: "--spec-ngram-size-m",
        label: "Spec ngram size M",
        description: "Draft m-gram length for ngram-simple / ngram-map (default: 48).",
        category: ParamCategory::Speculative,
        kind: int(1, 1024, 1, 48),
    ),
    lp!(
        key: "spec_ngram_min_hits",
        cli: "--spec-ngram-min-hits",
        label: "Spec ngram min hits",
        description: "Minimum hits for ngram-map (default: 1).",
        category: ParamCategory::Speculative,
        kind: int(0, 1000, 1, 1),
    ),

    // ─── TTS / Voice ─────────────────────────────────────────────────────────
    lp!(
        key: "model_vocoder",
        cli: "--model-vocoder",
        aliases: &["-mv"],
        label: "Vocoder model",
        description: "Vocoder model for audio generation.",
        category: ParamCategory::Tts,
        kind: text_k(""),
    ),
    lp!(
        key: "tts_use_guide_tokens",
        cli: "--tts-use-guide-tokens",
        label: "TTS guide tokens",
        description: "Use guide tokens to improve TTS word recall.",
        category: ParamCategory::Tts,
        kind: bool_k(false),
    ),

    // ─── Прочее / lookup / infill ────────────────────────────────────────────
    lp!(
        key: "lookup_cache_static",
        cli: "--lookup-cache-static",
        aliases: &["-lcs"],
        label: "Lookup cache (static)",
        description: "Static lookup cache for lookup decoding (not updated by generation).",
        category: ParamCategory::Other,
        kind: text_k(""),
    ),
    lp!(
        key: "lookup_cache_dynamic",
        cli: "--lookup-cache-dynamic",
        aliases: &["-lcd"],
        label: "Lookup cache (dynamic)",
        description: "Dynamic lookup cache (updated by generation).",
        category: ParamCategory::Other,
        kind: text_k(""),
    ),
    lp!(
        key: "reverse_prompt",
        cli: "--reverse-prompt",
        aliases: &["-r"],
        label: "Reverse prompt",
        description: "Halt generation at PROMPT (interactive mode).",
        category: ParamCategory::Other,
        kind: text_k(""),
    ),
    lp!(
        key: "special",
        cli: "--special",
        aliases: &["-sp"],
        label: "Special tokens",
        description: "Enable special tokens output (default: false).",
        category: ParamCategory::Other,
        kind: bool_k(false),
    ),
    lp!(
        key: "warmup",
        cli: "--warmup",
        aliases: &["--no-warmup"],
        label: "Warmup",
        description: "Perform warmup with empty run (default: enabled).",
        category: ParamCategory::Other,
        kind: bool_k(true),
    ),
    lp!(
        key: "spm_infill",
        cli: "--spm-infill",
        label: "SPM infill",
        description: "Use Suffix/Prefix/Middle pattern for infill (default: disabled).",
        category: ParamCategory::Other,
        kind: bool_k(false),
    ),
    lp!(
        key: "pooling",
        cli: "--pooling",
        label: "Pooling type",
        description: "Pooling type for embeddings: none/mean/cls/last/rank.",
        category: ParamCategory::Other,
        kind: enum_k(POOLING_TYPES, "none"),
        env: "LLAMA_ARG_POOLING",
    ),

    // ─── Готовые пресеты (downloads) ─────────────────────────────────────────
    lp!(
        key: "embd_gemma_default",
        cli: "--embd-gemma-default",
        label: "EmbeddingGemma (default)",
        description: "Use default EmbeddingGemma model (downloads weights).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_1_5b_default",
        cli: "--fim-qwen-1.5b-default",
        label: "FIM Qwen 1.5B",
        description: "Use default Qwen 2.5 Coder 1.5B (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_3b_default",
        cli: "--fim-qwen-3b-default",
        label: "FIM Qwen 3B",
        description: "Qwen 2.5 Coder 3B (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_7b_default",
        cli: "--fim-qwen-7b-default",
        label: "FIM Qwen 7B",
        description: "Qwen 2.5 Coder 7B (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_7b_spec",
        cli: "--fim-qwen-7b-spec",
        label: "FIM Qwen 7B + speculative",
        description: "Qwen 2.5 Coder 7B + 0.5B draft (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_14b_spec",
        cli: "--fim-qwen-14b-spec",
        label: "FIM Qwen 14B + speculative",
        description: "Qwen 2.5 Coder 14B + 0.5B draft (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "fim_qwen_30b_default",
        cli: "--fim-qwen-30b-default",
        label: "FIM Qwen 30B",
        description: "Qwen 3 Coder 30B A3B Instruct (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "gpt_oss_20b_default",
        cli: "--gpt-oss-20b-default",
        label: "gpt-oss 20B",
        description: "Use gpt-oss-20b (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "gpt_oss_120b_default",
        cli: "--gpt-oss-120b-default",
        label: "gpt-oss 120B",
        description: "Use gpt-oss-120b (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "vision_gemma_4b_default",
        cli: "--vision-gemma-4b-default",
        label: "Vision Gemma 3 4B QAT",
        description: "Gemma 3 4B QAT (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "vision_gemma_12b_default",
        cli: "--vision-gemma-12b-default",
        label: "Vision Gemma 3 12B QAT",
        description: "Gemma 3 12B QAT (downloads).",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
    lp!(
        key: "spec_default",
        cli: "--spec-default",
        label: "Spec decoding default",
        description: "Enable default speculative decoding config.",
        category: ParamCategory::Presets,
        kind: bool_k(false),
    ),
];

// ─────────────────────────────────────────────────────────────────────────────
// Поиск
// ─────────────────────────────────────────────────────────────────────────────

pub fn by_key(key: &str) -> Option<&'static LlamaParam> {
    LLAMA_PARAMS.iter().find(|p| p.key == key)
}

pub fn params_in_category(cat: ParamCategory) -> impl Iterator<Item = &'static LlamaParam> {
    LLAMA_PARAMS.iter().filter(move |p| p.category == cat)
}

/// Дефолтное `ParamValue` для чипа при добавлении — соответствует `kind.default`.
pub fn default_value(kind: &ParamKind) -> crate::config::ParamValue {
    use crate::config::ParamValue;
    match kind {
        ParamKind::Int { default, .. } => ParamValue::Int(*default),
        ParamKind::Float { default, .. } => ParamValue::Float(*default),
        ParamKind::Bool { default } => ParamValue::Bool(*default),
        ParamKind::Text { default } => ParamValue::Text((*default).to_string()),
        ParamKind::Enum { default, .. } => ParamValue::Enum((*default).to_string()),
    }
}
